---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "**/*.md"
  exclude: posts.json
  new_doc_ext: md
  templates:
  - post
- type: document
  path: src/_data/placeData.json
  label: Place Tags
- type: document
  path: src/_data/settings.json
  label: Settings
upload_dir: trailcoffee
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run production
