backend:
  name: git-gateway
  branch: master
  repo: sts24/trailcoffee
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"
site_url: "https://trailcoffee.netlify.com"
show_preview_links: true
collections: 
  - name: "post"
    label: "Posts"
    folder: "src/posts"
    slug: "{{slug}}"
    preview_path: "/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Feautured Image", name: "image", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Title", name: "alt", widget: "string" }
